$: << File.join(File.dirname(__FILE__), "/../lib") 

require 'rubygems'
require 'treetop'
require 'active_support'

require 'interpreter/grammars/nudge_common'

require 'interpreter/grammars/nudge_value_helpers'
require 'interpreter/grammars/nudge_reference_helpers'
require 'interpreter/grammars/nudge_instruction_helpers'
require 'interpreter/grammars/nudge_codeblock_helpers'

require 'interpreter/grammars/nudge_reference'
require 'interpreter/grammars/nudge_instruction'
require 'interpreter/grammars/nudge_value'
require 'interpreter/grammars/nudge_codeblock'

require 'interpreter/nudge_program'

require 'interpreter/interpreter'
require 'interpreter/types/pushTypes'
require 'interpreter/types/codeType'
require 'interpreter/stack'
require 'interpreter/programPoints'

require 'instructions/infrastructure'

require 'instructions/stack_manipulation'
require 'instructions/int_arithmetic'
require 'instructions/float_arithmetic'
require 'instructions/float_transcendental'
require 'instructions/comparisons'
require 'instructions/conditionals'
require 'instructions/conversions'
require 'instructions/random_value'
require 'instructions/exec'
require 'instructions/name_bindings'
require 'instructions/name_basics'

# Dir.glob('instructions/bool/*.rb').each do |specfile|
#   require specfile
#   puts specfile
# end

require 'instructions/bool/bool_and'
require 'instructions/bool/bool_equal_q'
require 'instructions/bool/bool_not'
require 'instructions/bool/bool_or'
require 'instructions/bool/bool_xor'

require 'instructions/code/code_atom_q'
require 'instructions/code/code_backbone_points'
require 'instructions/code/code_car'
require 'instructions/code/code_cdr'
require 'instructions/code/code_concatenate'
require 'instructions/code/code_cons'
require 'instructions/code/code_container'
require 'instructions/code/code_contains_q'
require 'instructions/code/code_define'
require 'instructions/code/code_discrepancy'
require 'instructions/code/code_do_count'
require 'instructions/code/code_do_range'
require 'instructions/code/code_do_times'
require 'instructions/code/code_execute'
require 'instructions/code/code_execute_then_pop'
require 'instructions/code/code_gsub'
require 'instructions/code/code_instructions'
require 'instructions/code/code_list'
require 'instructions/code/code_member_q'
require 'instructions/code/code_name_lookup'
require 'instructions/code/code_noop'
require 'instructions/code/code_nth'
require 'instructions/code/code_nth_cdr'
require 'instructions/code/code_nth_point'
require 'instructions/code/code_null_q'
require 'instructions/code/code_parses_q'
require 'instructions/code/code_points'
require 'instructions/code/code_position'
require 'instructions/code/code_quote'
require 'instructions/code/code_replace_nth_point'
require 'instructions/code/code_atom_q'
require 'instructions/code/code_backbone_points'
require 'instructions/code/code_car'
require 'instructions/code/code_cdr'
require 'instructions/code/code_concatenate'
require 'instructions/code/code_cons'
require 'instructions/code/code_container'
require 'instructions/code/code_contains_q'
require 'instructions/code/code_define'
require 'instructions/code/code_discrepancy'
require 'instructions/code/code_do_count'
require 'instructions/code/code_do_range'
require 'instructions/code/code_do_times'
require 'instructions/code/code_execute'
require 'instructions/code/code_execute_then_pop'
require 'instructions/code/code_gsub'
require 'instructions/code/code_instructions'
require 'instructions/code/code_list'
require 'instructions/code/code_member_q'
require 'instructions/code/code_name_lookup'
require 'instructions/code/code_noop'
require 'instructions/code/code_nth'
require 'instructions/code/code_nth_cdr'
require 'instructions/code/code_nth_point'
require 'instructions/code/code_null_q'
require 'instructions/code/code_parses_q'
require 'instructions/code/code_points'
require 'instructions/code/code_position'
require 'instructions/code/code_quote'
require 'instructions/code/code_replace_nth_point'

include NudgeType