Feature: Name new
  In order to create new local variables
  As a modeler
  I want name_new to create an (arbitrary) new name string

  Scenario: name_new should generate a new name with a novel string
    Given context
    When event
    Then outcome
  
  Scenario: the name should never match any currently bound name
    Given context
    When event
    Then outcome
  
  Scenario: the name should never be regenerated by a subsequent name_new instruction
    Given context
    When event
    Then outcome
  
  
  
  